---
site:
  title: "LB2863: OpenShift Application Platform ROI Lab"
  url: https://github.com/rhpds/showroom_template_nookbag
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-2025/ui-bundle.zip
    # Using Summit 2025 theme for Summit 2026 compatibility
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui

asciidoc:
  attributes:
    showroom-collection-version: v1.5.2

runtime:
  fetch: true

output:
  dir: ./www
